name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: hojhon-site

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create docker-entrypoint.sh on runner
      run: |
        cat > docker-entrypoint.sh <<'SH'
        #!/bin/sh
        # Replace placeholder in the shipped index.html with the runtime Formspree URL
        if [ -n "$FORMSPREE_FORM_ID" ]; then
          sed -i "s|FORMSPREE_URL_PLACEHOLDER|https://formspree.io/f/$FORMSPREE_FORM_ID|g" /usr/share/nginx/html/index.html || true
        else
          echo "Warning: FORMSPREE_FORM_ID not set"
        fi
        exec "$@"
        SH
        chmod +x docker-entrypoint.sh


    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_REPOSITORY }}:latest
